version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
  frontend:
    build: ./frontend
    ports:
      - "3000:80" # Map container's 80 to host's 3000
    depends_on:
      - backend
