version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
<<<<<<< HEAD

  # Comment out or remove the frontend service during local development
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - backend
=======
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
>>>>>>> b9c875de4 (create app for the AI-pallete)
